import type { Metadata } from "next";
import "./globals.css";
import "../sass/style.scss";
import Header from "@/components/headers/header";
import { Providers } from "./providers";
import ClientLayout from "./client-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <ClientLayout>{children}</ClientLayout>
        </Providers>
      </body>
    </html>
  );
}